scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: web_app
  scrape_interval: 5s
  static_configs:
  - targets:
    - web_app:5000
